### ISSUE TITLE
Tradicionalista Lydros 

### ISSUE THREAD

**Issue by rsrmdp** [AdonisWOW/bugtracker#11]
### ¿Qué cliente usas?

esES

### Facción

Alianza

### Comportamiento Actual

En su dialogo no completa con el nombre del Personaje
Anuncia: `$gforastero:forastera;`

### Comportamiento Blizzlike Esperado

Debería mostrar una palabra, dependiendo del genero del personaje.
Forastero, en caso de ser masculino, o forastera, en caso de ser femenino.

### Fuente

- https://www.wowhead.com/wotlk/npc=14368/lorekeeper-lydros
- https://www.wowhead.com/wotlk/quest=7482/elven-legends

### Pasos para reproducir el problema

![image](https://github.com/user-attachments/assets/3a9243a0-050d-4714-976e-eceb6953c416)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/0ba59c0053ce

### Sistema operativo

Ubuntu 24.04

### Módulos

- [mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
- [mod-enabled-commands](https://github.com/pangolp/mod-enabled-commands)
- [mod-npc-promotion](https://github.com/pangolp/mod-npc-promotion)
- [mod-quest-loot-party](https://github.com/pangolp/mod-quest-loot-party)

### Personalizaciones

Ninguna

### Servidor

AdonisWOW

**Comment by pangolp** [comment]
Ya es parte del emulador el arregló.
Gracias por el reporte.
