### ISSUE TITLE
Traveler's Tundra Mammoth y Magic Rooster

### ISSUE THREAD

**Issue by JaElvf** [AdonisWOW/bugtracker#12]
### ¿Qué cliente usas?

enGB

### Facción

Alianza

### Comportamiento Actual

Al estar montado en el [Traveler's Tundra Mammoth](https://wowgaming.altervista.org/aowow/?spell=61425) (para abreviar TTM) y montar en el [Magic Rooster](https://wowgaming.altervista.org/aowow/?spell=65917) los NPCs del TTM se quedan en el Magic Rooster.

El error en si lo causa el Magic Rooster debido a que cuando te montas en el mismo si tienes puesta otra montura no te baja de esa montura antes de castear el Magic Rooster como tal, sino que lo hace estando montado.

Tambien esta el detalle que al demontar el TTM no expulsa a los NPC's pasajeros solo desaparecen junto con la montura.

### Comportamiento Blizzlike Esperado

1.- Al usar el Magic Rooster deberia de desmontar y recien castear la montura.
2.- Al momento de desmontar el Traveler's Tundra Mammoth los NPCs deberian ser expulados de la montura.
![image](https://github.com/user-attachments/assets/6138b3b6-7aa3-4474-9df0-429d445d9e72)
![image](https://github.com/user-attachments/assets/3da2a856-46b4-4cf4-a6ec-b888e2b510ea)

### Fuente

- https://wowgaming.altervista.org/aowow/?spell=61425
- https://wowgaming.altervista.org/aowow/?spell=65917
- https://wowgaming.altervista.org/aowow/?spell=66122

### Pasos para reproducir el problema

1.- Montar el [Traveler's Tundra Mammoth](https://wowgaming.altervista.org/aowow/?spell=61425)
2.- Montar el [Magic Rooster](https://wowgaming.altervista.org/aowow/?spell=65917)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/0ba59c0053ce

### Sistema operativo

Windows 10 Pro

### Módulos

- [mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
- [mod-enabled-commands](https://github.com/pangolp/mod-enabled-commands)
- [mod-npc-promotion](https://github.com/pangolp/mod-npc-promotion)
- [mod-quest-loot-party](https://github.com/pangolp/mod-quest-loot-party)

### Personalizaciones

Ninguna

### Servidor

AdonisWOW

**Comment by JaElvf** [comment]
Este problema creo que podría afectar tambien a monturas parecidas como la Choper o el Cohete de recluta a un amigo, pero eso  no lo probe. Pero debería tener el mismo comportamiento al montar el Magic Rooster los Personajes que esten montados seguiran estandolo con el Magic Rooster puesto.

**Comment by pangolp** [comment]
> Este problema creo que podría afectar tambien a monturas parecidas como la Choper o el Cohete de recluta a un amigo, pero eso no lo probe. Pero debería tener el mismo comportamiento al montar el Magic Rooster los Personajes que esten montados seguiran estandolo con el Magic Rooster puesto.

Buen reporte, quizás por discord, te voy a estar pidiendo un poco mas de detalle, para intentar replicar el fallo.

**Comment by pangolp** [comment]
Ya lo probé y entendí perfectamente el bug. Gracias por el reporte, tratare de buscar la solución en los próximos días.
Lo malo, es que nose si solamente pasa con esa montura o con otras, pero de momento, veremos eso.

**Comment by pangolp** [comment]
Es un fallo blizzlike, lo encontró Nefertum al comentario, de todos modos, vamos a intentar solucionarlo.
Pero no es algo del emulador, es algo que ya viene por defecto en la montura del pollo.
https://www.wowhead.com/wotlk/item=49290/magic-rooster-egg#comments:id=929888

> Interestingly enough, you can mount to this mount from another and not be dismounted on the cast. Probably a glitch, but all other mounts will dismount your current mount before mounting you on your new one.

> Just to confirm and add to this - if you're lucky enough to also have the Black Qiraji Battle Tank (Scarab Lord) and are riding it when you cast the magic rooster egg you actually keep both mount buffs on your character at the same time. This means that if you click off the magic rooster egg mount buff you're instantly back on the Battle Tank. Not really information that will be useful for a lot of people but an interesting tidbit nonetheless! :)

**Comment by pangolp** [comment]
Tengo 2 opciones respeto a este tema:
1. Le dejamos castear la `montura`, eliminando los vendedores.
2. Impedimos que pueda usar el `pollo`, si esta en una `montura`.

Puede que con la escoba de `Halloween` ocurra el mismo problema.
Pero es un fallo blizzlike, la verdad es que poco se puede hacer en este caso.

**Comment by pangolp** [comment]
Debido a que la comunidad, decide conservar este tipo de "fallos" porque son considerados blizzlike, respetamos esa decisión, pero hemos creado un modulo, que permite corregir este tipo de fallos. https://github.com/pangolp/mod-non-blizzlike-fixes. Todavía no lo añadí al servidor, pero en los próximos días, lo voy a añadir. Gracias por el reporte, lo doy por completado.
